<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTodoTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('todo', function (Blueprint $table) {
            $table->increments('id');
            $table->string('subject')->nullable();
            $table->integer('order')->nullable();
            $table->integer('parent')->nullable();
            $table->timestamp('due_date')->nullable();
            $table->mediumText('notes')->nullable();
            $table->tinyInteger('assignee')->nullable();
            $table->timestamp('reminded_at')->nullable();
            $table->morphs('todoable');
            $table->tinyInteger('is_visible')->default(0);
            $table->tinyInteger('completed')->default(0);
            $table->integer('user_id')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('todo');
    }
}
